name: Docker Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # once a month
    - cron: '0 0 1 * *'
  workflow_dispatch:
      

env:
  REGISTRY: ghcr.io
  GITHUB_REPOSITORY: kaovilai/gha-runner-container

jobs:
  build-and-publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get actions/runner latest release version
      id: latest_version
      run: |
        VERSION=$(curl --silent https://api.github.com/repos/actions/runner/releases/latest | jq -r '.tag_name')
        echo "RUNNER_VERSION=$VERSION" >> $GITHUB_ENV
        echo "::set-output name=runner_version::$VERSION"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:latest
          ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ steps.latest_version.outputs.runner_version }}
        platforms: linux/amd64,linux/arm64
